name: ekomarket
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  flutter_native_splash: ^2.2.19
  get: 4.6.5
  flutter: 
    sdk: flutter
  iconly: ^1.0.1
  zoom_tap_animation: ^1.1.0
  carousel_slider: ^4.2.1
  get_storage: ^2.1.1
  cached_network_image: ^3.2.3
  http: ^0.13.6
  google_maps_flutter: ^2.0.6
  flutter_rating_bar: ^4.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/welcome_screen_images/
    - assets/images/on_boarding_images/onboarding-image-1.png
    - assets/images/on_boarding_images/onboarding-image-2.png
    - assets/images/on_boarding_images/onboarding-image-3.png
    - assets/
